// AUTO-GENERATED by md-to-data.js — DO NOT EDIT DIRECTLY
// Edit 114-cooking/content.md instead, then run: npm run build
//
// Generated: 2026-07-05T07:45:56.791Z

window.PORTAL = {
  "meta": {
    "title": "學術能力模擬檢測入口",
    "subtitle": "歡迎來到模擬考試線上平台。本系統已依照不同試題與科目分類，請點擊下方對應的卡片進入考場進行線上作答與評分。"
  },
  "exams": [
    {
      "id": "exam-114-4-chinese",
      "tag": "國語文綜合能力測驗",
      "title": "114 學年度北北基模擬考試",
      "desc": "本測驗包含字音字形、國學基礎、古典詩文及白話文學閱讀，並包含混合/手寫非選擇題題型。內建學測多選扣分算式，並提供即時字數統計與詳細題目解析。",
      "time": "90 分鐘",
      "questions": "共 36 題",
      "score": "滿分 100 分",
      "href": "114-4-chinese/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-114-cooking",
      "tag": "中餐烹飪職種學科",
      "title": "114 學年度中餐烹飪學科測驗",
      "desc": "本測驗包含 114 學年度全國高級中等學校學生家事類技藝競賽中餐烹飪職種學科測驗共 50 題選擇題。涵蓋飲食文化與餐飲管理、食材與營養知識、烹飪技法與專業器具，提供即時評估與詳細出處解析。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "114-cooking/",
      "btnText": "進入線上考場"
    }
  ]
};