// AUTO-GENERATED by md-to-data.js — DO NOT EDIT DIRECTLY
// Edit 114-cooking/content.md instead, then run: npm run build
//
// Generated: 2026-07-07T00:08:34.141Z

window.PORTAL = {
  "meta": {
    "title": "線上考場入口",
    "subtitle": "整合各年度技藝競賽與技能檢定學科測驗，支援計時、評分與詳解複習。"
  },
  "exams": [
    {
      "id": "exam-115-chinese-cooking-b",
      "tag": "中餐葷食乙級",
      "title": "中餐葷食乙級學科測試參考資料",
      "desc": "115.07 版中餐葷食乙級學科題庫，共 676 題，涵蓋食物性質、選購、貯藏、製備、排盤裝飾、器具設備、營養、成本控制、衛生知識與衛生法規。",
      "time": "120 分鐘",
      "questions": "共 676 題",
      "score": "滿分 100 分",
      "href": "115-chinese-cooking-b/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-115-chinese-cooking-c",
      "tag": "中餐葷食丙級",
      "title": "中餐葷食丙級學科測試參考資料",
      "desc": "115.07 版中餐葷食丙級學科題庫，共 640 題，涵蓋食物性質、選購、貯存、製備、排盤裝飾、器具設備、營養、成本控制、衛生知識與衛生法規。",
      "time": "120 分鐘",
      "questions": "共 640 題",
      "score": "滿分 100 分",
      "href": "115-chinese-cooking-c/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-115-western-cooking-b",
      "tag": "西餐烹調乙級",
      "title": "西餐烹調乙級學科測試參考資料",
      "desc": "115.07 版西餐烹調乙級學科題庫，共 548 題，涵蓋食物性質及選購、貯存、製備、器皿盤飾、設備器具、營養、成本控制、安全措施、衛生知識與衛生法規。",
      "time": "120 分鐘",
      "questions": "共 548 題",
      "score": "滿分 100 分",
      "href": "115-western-cooking-b/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-115-western-cooking-c",
      "tag": "西餐烹調丙級",
      "title": "西餐烹調丙級學科測試參考資料",
      "desc": "115.07 版西餐烹調丙級學科題庫，共 519 題，涵蓋食物性質及選購、貯存、製備、器皿盤飾、設備器具、營養、成本控制、安全措施、衛生知識與衛生法規。",
      "time": "120 分鐘",
      "questions": "共 519 題",
      "score": "滿分 100 分",
      "href": "115-western-cooking-c/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-115-baking-b",
      "tag": "烘焙乙級",
      "title": "烘焙乙級學科測試參考資料",
      "desc": "115.07 版烘焙乙級學科題庫，共 730 題，涵蓋產品分類、原料選用、產品製作、品質鑑定、包裝、食品保存、品質管制、成本計算與食品良好衛生規範。",
      "time": "120 分鐘",
      "questions": "共 730 題",
      "score": "滿分 100 分",
      "href": "115-baking-b/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-115-baking-c",
      "tag": "烘焙丙級",
      "title": "烘焙丙級學科測試參考資料",
      "desc": "115.07 版烘焙丙級學科題庫，共 513 題，涵蓋產品分類、原料選用、產品製作、品質鑑定、烘焙食品包裝與食品貯存。",
      "time": "120 分鐘",
      "questions": "共 513 題",
      "score": "滿分 100 分",
      "href": "115-baking-c/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-101-chinese-cooking",
      "tag": "中餐烹調",
      "title": "101 學年度中餐烹調正式競賽學科",
      "desc": "101 學年度商業類科學生技藝競賽中餐烹調正式學科試卷，共 50 題，涵蓋食材部位、菜系文化、烹調技法、食品安全與地方飲食。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "101-chinese-cooking/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-102-chinese-cooking",
      "tag": "中餐烹調",
      "title": "102 學年度中餐烹調正式競賽學科",
      "desc": "102 學年度商業類科學生技藝競賽中餐烹調學科試題，共 50 題，涵蓋食材來源、菜系文化、烹調技法、食品安全、庫房管理與成本換算。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "102-chinese-cooking/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-103-chinese-cooking",
      "tag": "中餐烹調",
      "title": "103 學年度中餐烹調正式競賽學科",
      "desc": "103 學年度商業類科學生技藝競賽中餐烹調正式學科試卷，共 50 題，涵蓋食材特性、菜系文化、食品安全、庫房管理、地方特產與度量衡。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "103-chinese-cooking/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-104-chinese-cooking",
      "tag": "中餐烹調",
      "title": "104 學年度中餐烹調正式競賽學科",
      "desc": "104 學年度商業類科學生技藝競賽中餐烹飪正式學科試卷，共 50 題，涵蓋米食黏度、食材產季、器具安全、菜單順序、食品安全與宴席文化。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "104-chinese-cooking/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-104-chinese-cooking-mock",
      "tag": "中餐烹調",
      "title": "104 學年度中餐烹調模擬試題學科",
      "desc": "104 學年度商業類科學生技藝競賽中餐烹飪模擬學科試卷，共 50 題，涵蓋調味、食材部位、菜系文化、食品安全、地方特產與烹調技法。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "104-chinese-cooking-mock/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-105-chinese-cooking",
      "tag": "中餐烹調",
      "title": "105 學年度中餐烹調正式試題學科",
      "desc": "105 學年度商業類科學生技藝競賽中餐烹飪正式學科試卷，共 50 題，涵蓋調味、食材部位、菜系文化、食品安全、地方特產與烹調技法。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "105-chinese-cooking/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-106-chinese-cooking-h",
      "tag": "中餐烹調",
      "title": "106H 中餐烹飪學科試題",
      "desc": "106 學年度商業類科學生技藝競賽中餐烹飪學科試題，共 50 題，涵蓋中餐史、廚房安全、食材分類、營養、食品安全與烹調技法。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "106-chinese-cooking-h/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-106-chinese-cooking-mock",
      "tag": "中餐烹調",
      "title": "106 學年度中餐烹調模擬試卷學科",
      "desc": "106 學年度商業類科學生技藝競賽中餐烹調模擬試卷，共 50 題，涵蓋菜系文化、食材部位、烹調技法、食品安全、營養與單位換算。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "106-chinese-cooking-mock/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-107-chinese-cooking-h",
      "tag": "中餐烹調",
      "title": "107 學年度 H 中餐烹飪正式試題",
      "desc": "107 學年度商業類科學生技藝競賽 H 中餐烹飪正式學科試題，共 50 題，含答案疑義題，涵蓋廚房安全、食材分類、菜系文化、食品衛生、營養與烹調技法。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "107-chinese-cooking-h/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-108-chinese-cooking-h",
      "tag": "中餐烹調",
      "title": "108 學年度 H 中餐烹飪正式試題",
      "desc": "108 學年度商業類科學生技藝競賽 H 中餐烹飪正式學科試題，共 50 題，含送分與答案疑義題，涵蓋中餐史、食材分類、菜系文化、食品衛生、營養與烹調技法。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "108-chinese-cooking-h/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-109-chinese-cooking",
      "tag": "中餐烹調",
      "title": "109 年度中餐烹飪正式試題",
      "desc": "109 年度商業類學生技藝競賽中餐烹飪學科正式試題，共 50 題，涵蓋廚房分工、食材儲存、米食點心、菜系文化、食品衛生與烹調技法。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "109-chinese-cooking/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-110-chinese-cooking",
      "tag": "中餐烹調",
      "title": "110 學年度中餐烹飪正式試題",
      "desc": "110 學年度商業類學生技藝競賽中餐烹飪學科正式試題，共 50 題，涵蓋競賽規範、食品衛生、食材處理、米食點心、菜系文化與烹調技法。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "110-chinese-cooking/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-111-chinese-cooking-h",
      "tag": "中餐烹調",
      "title": "111 學年度 H 中餐烹飪學科試題",
      "desc": "111 學年度商業類學生技藝競賽 H 中餐烹飪學科試題，共 50 題，涵蓋競賽規範、食品衛生、食材處理、米食點心、菜系文化與烹調技法。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "111-chinese-cooking-h/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-112-cooking-contest",
      "tag": "技藝競賽學科",
      "title": "112學年度中餐烹飪學科正式試題",
      "desc": "本測驗包含 112 學年度全國高級中等學校商業類學生技藝競賽中餐烹飪職種學科正式試題共 50 題選擇題。涵蓋飲食文化與菜系特色、食材與營養標章、烹飪實務與衛生安全，提供即時評估與詳細學理分析。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "112-cooking-contest/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-113-cooking-contest",
      "tag": "技藝競賽學科",
      "title": "113學年度中餐烹飪學科正式試題",
      "desc": "本測驗包含 113 學年度全國高級中等學校學生家事類技藝競賽中餐烹飪職種學科正式試題共 50 題選擇題。涵蓋飲食文化與菜系特色、食材與營養標章、烹飪實務與衛生安全，提供即時評估與詳細學理分析。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "113-cooking-contest/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-114-cooking",
      "tag": "中餐烹飪職種學科",
      "title": "114 學年度中餐烹飪學科測驗",
      "desc": "本測驗包含 114 學年度全國高級中等學校學生家事類技藝競賽中餐烹飪職種學科測驗共 50 題選擇題。涵蓋飲食文化與餐飲管理、食材與營養知識、烹飪技法與專業器具，提供即時評估與詳細出處解析。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "114-cooking/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-100-baking",
      "tag": "烘焙職種",
      "title": "100 學年度烘焙職種學科正式試卷",
      "desc": "100 學年度商業類科學生技藝競賽烘焙職種學科正式試卷，共 50 題，涵蓋烘焙原料功能、配方計算、產品製作、烤焙控制、包裝保存與品質判斷。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "100-baking/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-100-chinese-cooking",
      "tag": "中餐烹調",
      "title": "100 學年度中餐烹飪職種學科正式試卷",
      "desc": "100 學年度商業類科學生技藝競賽中餐烹飪職種學科正式試卷，共 50 題，涵蓋廚房衛生、食材別稱、菜系代表菜、烹調技法、肉品部位、調味與地方名產。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "100-chinese-cooking/",
      "btnText": "進入線上考場"
    },
    {
      "id": "exam-101-baking",
      "tag": "烘焙職種",
      "title": "101 學年度烘焙職種學科正式試卷",
      "desc": "101 學年度商業類科學生技藝競賽烘焙職種學科正式試卷，共 50 題，涵蓋烘焙原料功能、配方計算、產品製作、烤焙控制、包裝保存與品質判斷。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "101-baking/",
      "btnText": "進入測驗"
    },
    {
      "id": "exam-102-baking",
      "tag": "烘焙職種",
      "title": "102 學年度烘焙職種學科正式試卷",
      "desc": "102 學年度商業類科學生技藝競賽烘焙職種學科正式試卷，共 50 題，涵蓋烘焙原料功能、營養與配方計算、產品製作、食品添加物、包裝保存與品質判斷。",
      "time": "60 分鐘",
      "questions": "共 50 題",
      "score": "滿分 100 分",
      "href": "102-baking/",
      "btnText": "進入測驗"
    }
  ]
};